# Generated by Django 5.1.4 on 2024-12-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Enter the phone number (up to 15 digits).', max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(help_text='Unique identifier for the product.', max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_period',
            field=models.PositiveIntegerField(help_text='Warranty duration in months (must be positive).', verbose_name='Warranty Period (Months)'),
        ),
    ]
